#include<stdio.h>
#include<conio.h>
void main()
{int a,b;
printf("ENTER TWO NUMBERS:::");
scanf("%d",&a);
scanf("%d",&b);
printf("YOUR SUM IS:::");
printf("%d",a+b);
printf("\nYOUR DIFFERENCE IS::");
printf("%d",a-b);
printf("\nYOUR MULTIPLICATION IS:::");
printf("%d",a*b);
printf("\nYOUR  QUOTEIENT IS :::"):
printf("%d",a/b);
printf("\nYOUR REMAINDER IS:::");
printf("%d",a%b);
printf("\n\n\n\t\t\t\t\t MANISH CHOUHAN");
getch();
}